# Boiled down from cmake-converter outcome

cmake_minimum_required(VERSION 3.16.0 FATAL_ERROR)

project(binutils C)

################################################################################
# Sub-projects
################################################################################

set(PROJECT_NAME binutils)

################################################################################
# Source groups
################################################################################
set(Header_Files
    "aout-target.h"
    "aoutx.h"
    "as.h"
    "asintl.h"
    "attribute.h"
    "bfd.h"
    "bfdlink.h"
    "bfdver.h"
    "bignum.h"
    "binutils/config.h"
    "bucomm.h"
    "budbg.h"
    "cdefs.h"
    "coff-bfd.h"
    "coffcode.h"
    "coffswap.h"
    "config.h"
    "cp-demangle.h"
    "debug.h"
    "defs.h"
    "demanguse.h"
    "disassemble.h"
    "dwarf.h"
    "dwarf2dbg.h"
    "elf-bfd.h"
    "elf-linker-x86.h"
    "elf-linux-core.h"
    "elf-vxworks.h"
    "elf32-target.h"
    "elf64-target.h"
    "elfcode.h"
    "elfcomm.h"
    "elfcore.h"
    "elfxx-x86.h"
    "expr.h"
    "flexmember.h"
    "flonum.h"
    "frags.h"
    "genlink.h"
    "getopt-for-windows/getopt.h"
    "hash.h"
    "hosts/x86-64linux.h"
    "idx.h"
    "include/ansidecl.h"
    "include/aout/aout64.h"
    "include/aout/ar.h"
    "include/aout/ranlib.h"
    "include/aout/stab_gnu.h"
    "include/bfdlink.h"
    "include/coff/ecoff.h"
    "include/coff/external.h"
    "include/coff/i386.h"
    "include/coff/internal.h"
    "include/coff/msdos.h"
    "include/coff/pe.h"
    "include/coff/sym.h"
    "include/coff/x86_64.h"
    "include/ctf-api.h"
    "include/ctf.h"
    "include/demangle.h"
    "include/diagnostics.h"
    "include/dis-asm.h"
    "include/dwarf2.h"
    "include/elf/bpf.h"
    "include/elf/common.h"
    "include/elf/dwarf.h"
    "include/elf/external.h"
    "include/elf/i386.h"
    "include/elf/internal.h"
    "include/elf/reloc-macros.h"
    "include/elf/vxworks.h"
    "include/elf/x86-64.h"
    "include/environ.h"
    "include/filenames.h"
    "include/fnmatch.h"
    "include/fopen-same.h"
    "include/gdb/gdb-index.h"
    "include/hashtab.h"
    "include/libiberty.h"
    "include/objalloc.h"
    "include/opcode/i386.h"
    "include/opcode/riscv-opc.h"
    "include/plugin-api.h"
    "include/safe-ctype.h"
    "include/sframe-api.h"
    "include/sframe.h"
    "include/splay-tree.h"
    "include/symcat.h"
    "intprops.h"
    "libaout.h"
    "libbfd.h"
    "libc-config.h"
    "libcoff.h"
    "libecoff.h"
    "libpei.h"
    "listing.h"
    "obj-elf.h"
    "obj-format.h"
    "obj.h"
    "objdump.h"
    "opcodes/i386-opc.h"
    "opintl.h"
    "peicode.h"
    "plugin.h"
    "portability.h"
    "read.h"
    "sframe-impl.h"
    "swap.h"
    "symbols.h"
    "sysdep.h"
    "targ-cpu.h"
    "targ-env.h"
    "targmatch.h"
    "tc-i386.h"
    "tc.h"
    "te-linux.h"
    "verify.h"
    "vprintf-support.h"
    "wmemchr-impl.h"
    "write.h"
)
source_group("Header Files" FILES ${Header_Files})

set(Source_Files
    "alloca.c"
    "aout-cris.c"
    "aout32.c"
    "aout64.c"
    "archive.c"
    "archive64.c"
    "archures.c"
    "argv.c"
    "asprintf.c"
    "bfd.c"
    "bfdio.c"
    "binary.c"
    "bucomm.c"
    "cache.c"
    "coff-bfd.c"
    "coff-x86_64.c"
    "coffgen.c"
    "cofflink.c"
    "compress.c"
    "concat.c"
    "corefile.c"
    "cp-demangle.c"
    "cp-demint.c"
    "cplus-dem.c"
    "cpu-nios2.c"
    "d-demangle.c"
    "debug.c"
    "demanguse.c"
    "dis-buf.c"
    "dis-init.c"
    "disassemble.c"
    "dwarf.c"
    "dwarf1.c"
    "dwarf2.c"
    "dwarfnames.c"
    "elf-attrs.c"
    "elf-eh-frame.c"
    "elf-ifunc.c"
    "elf-properties.c"
    "elf-sframe.c"
    "elf-strtab.c"
    "elf-vxworks.c"
    "elf.c"
    "elf32.c"
    "elf32-nios2.c"
    "elf64-gen.c"
    "elf64-x86-64.c"
    "elf64.c"
    "elfcomm.c"
    "elflink.c"
    "elfxx-x86.c"
    "ffs.c"
    "filemode.c"
    "filename_cmp.c"
    "fnmatch.c"
    "format.c"
    "gen-aout.c"
    "getopt-for-windows/getopt.c"
    "getpagesize.c"
    "getpwd.c"
    "hash.c"
    "hashtab.c"
    "hex.c"
    "host-aout.c"
    "ihex.c"
    "lbasename.c"
    "libbfd.c"
    "linker.c"
    "lrealpath.c"
    "make-relative-prefix.c"
    "make-temp-file.c"
    "mbsinit.c"
    "mempcpy.c"
    "merge.c"
    "mkstemps.c"
    "objalloc.c"
    "objdump.c"
    "opncls.c"
    "pe-x86_64.c"
    "pei-x86_64.c"
    "pex64igen.c"
    "plugin.c"
    "portability.c"
    "prdbg.c"
    "rdcoff.c"
    "rddbg.c"
    "reloc.c"
    "rust-demangle.c"
    "safe-ctype.c"
    "section.c"
    "sframe-dump.c"
    "sframe-error.c"
    "sframe.c"
    "simple.c"
    "splay-tree.c"
    "srec.c"
    "stab-syms.c"
    "stabs.c"
    "strcasecmp.c"
    "strncasecmp.c"
    "syms.c"
    "targets.c"
    "tekhex.c"
    "unlink-if-ordinary.c"
    "vasprintf.c"
    "verilog.c"
    "version.c"
    "vprintf-support.c"
    "wmemchr.c"
    "wmempcpy.c"
    "wrstabs.c"
    "xexit.c"
    "xmalloc.c"
    "xstrdup.c"
    "xstrerror.c"
)
source_group("Source Files" FILES ${Source_Files})

set(ALL_FILES
    ${Header_Files}
    ${Source_Files}
)

################################################################################
# Target
################################################################################
add_library(${PROJECT_NAME} STATIC ${ALL_FILES})

set(ROOT_NAMESPACE binutils)

################################################################################
# Include directories
################################################################################
target_include_directories(${PROJECT_NAME} PUBLIC
	"${CMAKE_CURRENT_SOURCE_DIR}/include/elf"
	"${CMAKE_CURRENT_SOURCE_DIR}/include"
	"${CMAKE_CURRENT_SOURCE_DIR}/dirent/include"
	"${CMAKE_CURRENT_SOURCE_DIR}/getopt-for-windows"
	"${CMAKE_CURRENT_SOURCE_DIR}"
)

################################################################################
# Compile definitions
################################################################################
target_compile_definitions(${PROJECT_NAME} PRIVATE "BFD_BUILDING")

################################################################################
# Dependencies
################################################################################
find_package(ZLIB REQUIRED)
target_link_libraries(${PROJECT_NAME} ZLIB::ZLIB)
